# Create Our Cars
car1 = OurCar.create(:name => "1931 Chrysler CD Deluxe Roadster", :description => "Our favorite car", :thumb => "thumbs/31CD-main.jpg")
image1 = car1.our_car_images.create(:image_path => "31CD-1.jpg", :description => "")
image2 = car1.our_car_images.create(:image_path => "31CD-2.jpg", :description => "")
image3 = car1.our_car_images.create(:image_path => "31CD-3.jpg", :description => "")
image4 = car1.our_car_images.create(:image_path => "31CD-4.jpg", :description => "")
image5 = car1.our_car_images.create(:image_path => "31CD-5.jpg", :description => "")
image6 = car1.our_car_images.create(:image_path => "31CD-6.jpg", :description => "")
image7 = car1.our_car_images.create(:image_path => "31CD-7.jpg", :description => "")
image8 = car1.our_car_images.create(:image_path => "31CD-8.jpg", :description => "")
image9 = car1.our_car_images.create(:image_path => "31CD-9.jpg", :description => "")
image9 = car1.our_car_images.create(:image_path => "31CD-10.jpg", :description => "")

car2 = OurCar.create(:name => "1956 Chrysler Imperial Southampton", :description => "Our other favorite car", :thumb => "thumbs/56SH-main.jpg")
image1 = car2.our_car_images.create(:image_path => "56SH-1.jpg", :description => "")
image2 = car2.our_car_images.create(:image_path => "56SH-2.jpg", :description => "Jeff installing the restored door panel")
image3 = car2.our_car_images.create(:image_path => "56SH-3.jpg", :description => "Drive-Through Tree, Oregon")
image4 = car2.our_car_images.create(:image_path => "56SH-4.jpg", :description => "")
image5 = car2.our_car_images.create(:image_path => "56SH-5.jpg", :description => "Bryce Canyon, Utah")
image6 = car2.our_car_images.create(:image_path => "56SH-6.jpg", :description => "A bearded Gary Goers putting the finishing touches on the back seat")
image7 = car2.our_car_images.create(:image_path => "56SH-7.jpg", :description => "")
image8 = car2.our_car_images.create(:image_path => "56SH-8.jpg", :description => "")
image9 = car2.our_car_images.create(:image_path => "56SH-9.jpg", :description => "Seats, before and after")

car3 = OurCar.create(:name => "1965 Plymouth Valiant Station Wagon", :description => "Our blue favorite car", :thumb => "thumbs/65PV-main.jpg")
image1 = car3.our_car_images.create(:image_path => "65PV-1.jpg", :description => "")
image2 = car3.our_car_images.create(:image_path => "65PV-2.jpg", :description => "")
image3 = car3.our_car_images.create(:image_path => "65PV-3.jpg", :description => "")
image4 = car3.our_car_images.create(:image_path => "65PV-4.jpg", :description => "")

car4 = OurCar.create(:name => "61 New Yorker Convertible", :description => "Our old favorite car", :thumb => "thumbs/61NY-main.jpg")
image1 = car4.our_car_images.create(:image_path => "61NY-1.jpg", :description => "")
image2 = car4.our_car_images.create(:image_path => "61NY-2.jpg", :description => "")
image3 = car4.our_car_images.create(:image_path => "61NY-3.jpg", :description => "")
image4 = car4.our_car_images.create(:image_path => "61NY-4.jpg", :description => "")
image5 = car4.our_car_images.create(:image_path => "61NY-5.jpg", :description => "At the shop")
image6 = car4.our_car_images.create(:image_path => "61NY-6.jpg", :description => "")
image7 = car4.our_car_images.create(:image_path => "61NY-7.jpg", :description => "With our late friend Jim Harris' Ghia limousine (1994)")
image8 = car4.our_car_images.create(:image_path => "61NY-8.jpg", :description => "")
image9 = car4.our_car_images.create(:image_path => "61NY-9.jpg", :description => "Lisa in the New Yorker convertible at Mt St Helens (Fall 2003)")

car5 = OurCar.create(:name => "1956 Chrysler 300B", :description => "Our other favorite car", :thumb => "thumbs/56300B-main.jpg")
image1 = car5.our_car_images.create(:image_path => "56300B-1.jpg", :description => "")
image2 = car5.our_car_images.create(:image_path => "56300B-2.jpg", :description => "August 2008, Walter P Chrysler Club Regional Meet, McMinnville, Oregon")
image3 = car5.our_car_images.create(:image_path => "56300B-3.jpg", :description => "August 2008, Walter P Chrysler Club Regional Meet, McMinnville, Oregon")
image4 = car5.our_car_images.create(:image_path => "56300B-4.jpg", :description => "July 2008, Montana")
image5 = car5.our_car_images.create(:image_path => "56300B-5.jpg", :description => "July 2008, Montana")
image6 = car5.our_car_images.create(:image_path => "56300B-6.jpg", :description => "")
image7 = car5.our_car_images.create(:image_path => "56300B-7.jpg", :description => "July 2008, Montana")
image8 = car5.our_car_images.create(:image_path => "56300B-8.jpg", :description => "July 2008, Montana")
image9 = car5.our_car_images.create(:image_path => "56300B-9.jpg", :description => "")
image10 = car5.our_car_images.create(:image_path => "56300B-10.jpg", :description => "")
image11 = car5.our_car_images.create(:image_path => "56300B-11.jpg", :description => "Winter 2007")
image12 = car5.our_car_images.create(:image_path => "56300B-12.jpg", :description => "March 2006 - at JC Auto Restoration")
image13 = car5.our_car_images.create(:image_path => "56300B-13.jpg", :description => "July 2008, Wallace, Idaho")
image14 = car5.our_car_images.create(:image_path => "56300B-14.jpg", :description => "March 2006 - at JC Auto Restoration")